// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/reports/compare": {
            "post": {
                "description": "Compare metrics between two test runs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Compare test runs",
                "parameters": [
                    {
                        "description": "Comparison request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CompareTestRunsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/reporting.ComparisonResult"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/share": {
            "post": {
                "description": "Generate a shareable report with a unique URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Create shareable report",
                "parameters": [
                    {
                        "description": "Report request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateShareableReportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/shared": {
            "get": {
                "description": "List all active (non-expired) shared reports",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "List shared reports",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reporting.StoredReport"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/reports/shared/{id}": {
            "get": {
                "description": "Retrieve a shared report by ID",
                "tags": [
                    "reports"
                ],
                "summary": "Get shared report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a shared report by ID",
                "tags": [
                    "reports"
                ],
                "summary": "Delete shared report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/reports/stats": {
            "get": {
                "description": "Get statistics about stored reports",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get report statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/test-runs/{id}/export": {
            "get": {
                "description": "Export test run results in JSON, CSV, or HTML format",
                "tags": [
                    "reports"
                ],
                "summary": "Export test run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Export format (json, csv, html)",
                        "name": "format",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/test-runs/{id}/sla": {
            "post": {
                "description": "Check if test run meets specified SLA criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Check SLA",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SLA criteria",
                        "name": "criteria",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CheckSLARequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/reporting.SLAResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CheckSLARequest": {
            "type": "object",
            "required": [
                "max_avg_response_time",
                "max_p95",
                "max_p99",
                "min_requests_per_second",
                "min_success_rate"
            ],
            "properties": {
                "max_avg_response_time": {
                    "type": "number",
                    "minimum": 0
                },
                "max_p95": {
                    "type": "number",
                    "minimum": 0
                },
                "max_p99": {
                    "type": "number",
                    "minimum": 0
                },
                "min_requests_per_second": {
                    "type": "number",
                    "minimum": 0
                },
                "min_success_rate": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                }
            }
        },
        "handler.CompareTestRunsRequest": {
            "type": "object",
            "required": [
                "baseline_run_id",
                "comparison_run_id"
            ],
            "properties": {
                "baseline_run_id": {
                    "type": "string"
                },
                "comparison_run_id": {
                    "type": "string"
                }
            }
        },
        "handler.CreateShareableReportRequest": {
            "type": "object",
            "required": [
                "format",
                "test_run_id",
                "ttl_hours"
            ],
            "properties": {
                "format": {
                    "type": "string",
                    "enum": [
                        "json",
                        "csv",
                        "html"
                    ]
                },
                "test_run_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "ttl_hours": {
                    "description": "1 hour to 7 days",
                    "type": "integer",
                    "maximum": 168,
                    "minimum": 1
                }
            }
        },
        "model.Metrics": {
            "type": "object",
            "properties": {
                "active_workers": {
                    "type": "integer"
                },
                "avg_latency_ms": {
                    "type": "number"
                },
                "current_rps": {
                    "type": "number"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "failed_requests": {
                    "type": "integer"
                },
                "last_updated": {
                    "type": "string"
                },
                "max_latency_ms": {
                    "type": "number"
                },
                "min_latency_ms": {
                    "type": "number"
                },
                "p50_latency_ms": {
                    "type": "number"
                },
                "p75_latency_ms": {
                    "type": "number"
                },
                "p95_latency_ms": {
                    "type": "number"
                },
                "p99_latency_ms": {
                    "type": "number"
                },
                "requests_per_sec": {
                    "type": "number"
                },
                "run_id": {
                    "type": "string"
                },
                "status_codes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "success_requests": {
                    "type": "integer"
                },
                "total_duration_ms": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                }
            }
        },
        "model.StopReason": {
            "type": "string",
            "enum": [
                "completed",
                "cancelled",
                "failed"
            ],
            "x-enum-comments": {
                "ReasonCancelled": "User cancelled",
                "ReasonCompleted": "Normal completion",
                "ReasonFailed": "Error or SLA violation"
            },
            "x-enum-descriptions": [
                "Normal completion",
                "User cancelled",
                "Error or SLA violation"
            ],
            "x-enum-varnames": [
                "ReasonCompleted",
                "ReasonCancelled",
                "ReasonFailed"
            ]
        },
        "model.TestRun": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.TestRunStatus"
                },
                "stop_reason": {
                    "description": "How the run ended",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.StopReason"
                        }
                    ]
                }
            }
        },
        "model.TestRunStatus": {
            "type": "string",
            "enum": [
                "running",
                "completed",
                "cancelled",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusRunning",
                "StatusCompleted",
                "StatusCancelled",
                "StatusFailed"
            ]
        },
        "reporting.ComparisonResult": {
            "type": "object",
            "properties": {
                "baseline_metrics": {
                    "$ref": "#/definitions/model.Metrics"
                },
                "baseline_run": {
                    "$ref": "#/definitions/model.TestRun"
                },
                "compare_metrics": {
                    "$ref": "#/definitions/model.Metrics"
                },
                "compared_at": {
                    "type": "string"
                },
                "comparison_run": {
                    "$ref": "#/definitions/model.TestRun"
                },
                "differences": {
                    "$ref": "#/definitions/reporting.MetricDifferences"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "reporting.DiffValue": {
            "type": "object",
            "properties": {
                "absolute_diff": {
                    "type": "number"
                },
                "baseline": {
                    "type": "number"
                },
                "comparison": {
                    "type": "number"
                },
                "degraded": {
                    "type": "boolean"
                },
                "improved": {
                    "type": "boolean"
                },
                "percentage_diff": {
                    "type": "number"
                }
            }
        },
        "reporting.ExportFormat": {
            "type": "string",
            "enum": [
                "json",
                "csv",
                "html"
            ],
            "x-enum-varnames": [
                "FormatJSON",
                "FormatCSV",
                "FormatHTML"
            ]
        },
        "reporting.MetricDifferences": {
            "type": "object",
            "properties": {
                "avg_response_time": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "failed_requests": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "max_response_time": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "min_response_time": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "p50": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "p75": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "p95": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "p99": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "requests_per_second": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "success_rate": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "successful_requests": {
                    "$ref": "#/definitions/reporting.DiffValue"
                },
                "total_requests": {
                    "$ref": "#/definitions/reporting.DiffValue"
                }
            }
        },
        "reporting.SLAResult": {
            "type": "object",
            "properties": {
                "checked_at": {
                    "type": "string"
                },
                "met": {
                    "type": "boolean"
                },
                "violations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "reporting.StoredReport": {
            "type": "object",
            "properties": {
                "access_count": {
                    "type": "integer"
                },
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/reporting.ExportFormat"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
